name: HCAN Sourcing
markdown: redcarpet
highlighter: pygments
exclude: ["node_modules", "gulpfile.js", "package.json"]
logo: /assets/img/hb-logo.svg
author: Glen Hodges
#url: http://demo.rankhigher.ca/
permalinks: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap